---
leaders:
  - combat_value: 3
    place_unit_ability: 3

  - combat_value: 2
    place_unit_ability: 2

  - combat_value: 2
    place_unit_ability: 1
    special_effect: "if win combat"

  - combat_value: 1
    place_unit_ability: 2
    special_effect: "+2 if played in Wood or Rough column."

  - combat_value: 1
    place_unit_ability: 1
    special_effect: "+2 if played with 2x Chariots"

  - combat_value: 1
    place_unit_ability: 1
    special_effect: "+2 if played with 2x Slingers"

  - combat_value: 1
    place_unit_ability: 1
    special_effect: "+2 if played with 2x Warband Medium Infantry"

  - combat_value: -1
    place_unit_ability: 1

units:
  - unit_type: "Warband_Med_Inf"
    speed: 2
    attack_strength: 4
    defence_strength: 2

  - unit_type: "Slingers"
    speed: 3
    attack_strength: 1
    defence_strength: 1
    combine_ability: true

  - unit_type: "Chariots"
    speed: 3
    attack_strength: 4
    defence_strength: 2

  - unit_type: "Light_Cavalry"
    speed: 5
    attack_strength: 1
    defence_strength: 1

counts:
  Warband_Med_Inf: 6
  Slingers: 6
  Chariots: 6
  Light_Cavalry: 4
